const ProductActionTypes = {
	GET_SINGLE_PRODUCT_START: "GET_SINGLE_PRODUCT_START",
	GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
	GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",
	ADD_PRODUCT_TO_RECENTLY_VIEWED: "ADD_PRODUCT_TO_RECENTLY_VIEWED",
};

export default ProductActionTypes;
