const ProductActionTypes = {
	GET_SINGLE_PRODUCT_START: "GET_SINGLE_PRODUCT_START",
	GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
	GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",
};

export default ProductActionTypes;
