const ProductActionTypes = {
	GET_SINGLE_PRODUCT_START: "GET_SINGLE_PRODUCT_START",
	GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
	GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",
	ADD_PRODUCT_TO_RECENTLY_VIEWED: "ADD_PRODUCT_TO_RECENTLY_VIEWED",
	SEARCH_PRODUCTS_START: "SEARCH_PRODUCTS_START",
	SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
	SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",
};

export default ProductActionTypes;
